### ISSUE TITLE
Leak

### ISSUE THREAD

**Issue by schemil053** [DarkModz-Official/Azubi-Projekt#11]
https://github.com/MyDark-me/Azubi-Projekt/commit/b687c0dc3b0722004fbe61a47ff3337dc3df7f97
Zugangdaten veröffentlicht, funktionieren.
`sqlPostgres = new SQLPostgres("81.169.168.24:5433", "postgres", "superpasswort", "azubiprojekt");`

**Comment by V01D-PH03N1X** [comment]
Ist in Ordnung da es nur eine Demodatenbank in einem Docker ist :) 
Danke für den Hinweis, wurde in diesem Commit bereits behoben. 
Die Datenbank wurde offline genommen. 

MfG Sebastian Schindler

**Comment by V01D-PH03N1X** [comment]
Aufgrund der Umstrukturierung meiner Server Infrastruktur ist diese Datenbank-Server nicht mehr existent. 

Somit wird der Issue geschlossen
