### ISSUE TITLE
AP-22-HTTP-Server-sendet-leere-response

### ISSUE THREAD

**Issue by V01D-PH03N1X** [DarkModz-Official/Azubi-Projekt#6]
🐞 **BUG** 🐞

Wie ist der Bug entstanden?
Warum kommt nur noch eine leere Response an?
Wie kann man es beheben?

🔁 **Fehler Wiederholung?** 🔁

Ja, Server Starten kleinen Moment warten bis er gestartet ist.
Nach dem Starten einfach "127.0.0.1:8001/" requesten. 
Nun erhältst du eine Leere Request. 

-------------------------------------------------------------------------

HTTP Request: 

```
GET http://127.0.0.1:8001/ HTTP/1.1
Accept: */*
```
 

Ergebnis von HTTP Request: 

```
org.apache.http.ConnectionClosedException

Premature end of Content-Length delimited message body (expected: 2.246; received: 0) 
```

**Comment by keksgauner** [comment]
Im Grunde einfach die Bytes nicht gemeinsam sondern nacheinander senden.
